# ============================================
# PostgreSQL Profile Configuration
# ============================================

database.type=postgresql

# ============================================
# Postgresql Configuration
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/oneGasDB
spring.datasource.username=${SQL_DB_USERNAME}
spring.datasource.password=${SQL_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate=OFF

# ============================================
# HikariCP Connection Pool Configuration
# ============================================
# Numero massimo di connessioni nel pool
spring.datasource.hikari.maximum-pool-size=100
# Connessioni minime mantenute idle nel pool
spring.datasource.hikari.minimum-idle=10
# Timeout per ottenere una connessione dal pool (ms)
spring.datasource.hikari.connection-timeout=10000

